import type { Metadata } from "next";
import "./globals.css";
import Notification from "@/app/component/Notification";
import Navbar from "@/app/component/Navbar";
import Footer from "@/app/component/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Notification />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
